// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CancelSubscriptionData, CancelSubscriptionErrors, CancelSubscriptionResponses, CreateCheckoutSessionData, CreateCheckoutSessionErrors, CreateCheckoutSessionResponses, CreatePortalSessionData, CreatePortalSessionErrors, CreatePortalSessionResponses, DeleteAccountData, DeleteAccountResponses, ExtractDocumentData, ExtractDocumentErrors, ExtractDocumentResponses, GetCurrentUserData, GetCurrentUserResponses, GetSessionData, GetSessionResponses, GetSessionStateData, GetSessionStateResponses, GetSubscriptionData, GetSubscriptionResponses, GetUserData, GetUserErrors, GetUserResponses, ParseDocumentData, ParseDocumentErrors, ParseDocumentResponses, RewriteDocumentData, RewriteDocumentErrors, RewriteDocumentResponses, SaveSessionStateData, SaveSessionStateErrors, SaveSessionStateResponses, SignInData, SignInErrors, SignInResponses, SignOutData, SignOutResponses, SignUpData, SignUpErrors, SignUpResponses, StripeWebhookData, StripeWebhookResponses, UpdateSubscriptionData, UpdateSubscriptionErrors, UpdateSubscriptionResponses, UploadDocumentData, UploadDocumentErrors, UploadDocumentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class AuthApi {
    /**
     * Login
     */
    public static signIn<ThrowOnError extends boolean = false>(options: Options<SignInData, ThrowOnError>) {
        return (options.client ?? client).post<SignInResponses, SignInErrors, ThrowOnError>({
            url: '/auth/sign-in',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Signup
     */
    public static signUp<ThrowOnError extends boolean = false>(options: Options<SignUpData, ThrowOnError>) {
        return (options.client ?? client).post<SignUpResponses, SignUpErrors, ThrowOnError>({
            url: '/auth/sign-up',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Sign Out
     */
    public static signOut<ThrowOnError extends boolean = false>(options?: Options<SignOutData, ThrowOnError>) {
        return (options?.client ?? client).get<SignOutResponses, unknown, ThrowOnError>({ url: '/auth/sign-out', ...options });
    }
    
    /**
     * Get Session
     */
    public static getSession<ThrowOnError extends boolean = false>(options?: Options<GetSessionData, ThrowOnError>) {
        return (options?.client ?? client).get<GetSessionResponses, unknown, ThrowOnError>({ url: '/auth/get-session', ...options });
    }
    
    /**
     * Delete Account
     */
    public static deleteAccount<ThrowOnError extends boolean = false>(options?: Options<DeleteAccountData, ThrowOnError>) {
        return (options?.client ?? client).delete<DeleteAccountResponses, unknown, ThrowOnError>({ url: '/auth/account', ...options });
    }
}

export class UserApi {
    /**
     * Get Current User
     */
    public static getCurrentUser<ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>) {
        return (options?.client ?? client).get<GetCurrentUserResponses, unknown, ThrowOnError>({ url: '/user/me', ...options });
    }
    
    /**
     * Get User
     */
    public static getUser<ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>) {
        return (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({ url: '/user/{id}', ...options });
    }
}

export class DocumentApi {
    /**
     * Upload Document
     */
    public static uploadDocument<ThrowOnError extends boolean = false>(options: Options<UploadDocumentData, ThrowOnError>) {
        return (options.client ?? client).post<UploadDocumentResponses, UploadDocumentErrors, ThrowOnError>({
            ...formDataBodySerializer,
            url: '/document/upload',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
    
    /**
     * Parse Document
     */
    public static parseDocument<ThrowOnError extends boolean = false>(options: Options<ParseDocumentData, ThrowOnError>) {
        return (options.client ?? client).post<ParseDocumentResponses, ParseDocumentErrors, ThrowOnError>({
            ...formDataBodySerializer,
            url: '/document/parse',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
    
    /**
     * Extract Document
     */
    public static extractDocument<ThrowOnError extends boolean = false>(options: Options<ExtractDocumentData, ThrowOnError>) {
        return (options.client ?? client).post<ExtractDocumentResponses, ExtractDocumentErrors, ThrowOnError>({
            url: '/document/extract',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Rewrite Document
     */
    public static rewriteDocument<ThrowOnError extends boolean = false>(options: Options<RewriteDocumentData, ThrowOnError>) {
        return (options.client ?? client).post<RewriteDocumentResponses, RewriteDocumentErrors, ThrowOnError>({
            url: '/document/rewrite',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class SubscriptionsApi {
    /**
     * Get By User Id
     */
    public static getSubscription<ThrowOnError extends boolean = false>(options?: Options<GetSubscriptionData, ThrowOnError>) {
        return (options?.client ?? client).get<GetSubscriptionResponses, unknown, ThrowOnError>({ url: '/subscriptions/subscription', ...options });
    }
    
    /**
     * Update Subscription
     */
    public static updateSubscription<ThrowOnError extends boolean = false>(options: Options<UpdateSubscriptionData, ThrowOnError>) {
        return (options.client ?? client).put<UpdateSubscriptionResponses, UpdateSubscriptionErrors, ThrowOnError>({
            url: '/subscriptions/subscription',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Cancel Subscription
     */
    public static cancelSubscription<ThrowOnError extends boolean = false>(options: Options<CancelSubscriptionData, ThrowOnError>) {
        return (options.client ?? client).post<CancelSubscriptionResponses, CancelSubscriptionErrors, ThrowOnError>({
            url: '/subscriptions/subscription/cancel',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Create Checkout Session
     */
    public static createCheckoutSession<ThrowOnError extends boolean = false>(options: Options<CreateCheckoutSessionData, ThrowOnError>) {
        return (options.client ?? client).post<CreateCheckoutSessionResponses, CreateCheckoutSessionErrors, ThrowOnError>({
            url: '/subscriptions/checkout',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Create Portal Session
     */
    public static createPortalSession<ThrowOnError extends boolean = false>(options: Options<CreatePortalSessionData, ThrowOnError>) {
        return (options.client ?? client).post<CreatePortalSessionResponses, CreatePortalSessionErrors, ThrowOnError>({
            url: '/subscriptions/portal',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Stripe Webhook
     */
    public static stripeWebhook<ThrowOnError extends boolean = false>(options?: Options<StripeWebhookData, ThrowOnError>) {
        return (options?.client ?? client).post<StripeWebhookResponses, unknown, ThrowOnError>({ url: '/subscriptions/webhook', ...options });
    }
}

export class SessionStateApi {
    /**
     * Get Session State
     */
    public static getSessionState<ThrowOnError extends boolean = false>(options?: Options<GetSessionStateData, ThrowOnError>) {
        return (options?.client ?? client).get<GetSessionStateResponses, unknown, ThrowOnError>({ url: '/session-state', ...options });
    }
    
    /**
     * Save Session State
     */
    public static saveSessionState<ThrowOnError extends boolean = false>(options: Options<SaveSessionStateData, ThrowOnError>) {
        return (options.client ?? client).post<SaveSessionStateResponses, SaveSessionStateErrors, ThrowOnError>({
            url: '/session-state',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
