// This file is auto-generated by @hey-api/openapi-ts

import type { CancelSubscriptionResponse, GetCurrentUserResponse, GetSessionResponse, GetUserResponse, SaveSessionStateResponse, SignInResponse, SignUpResponse, UpdateSubscriptionResponse } from './types.gen';

const userSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

const sessionSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    if (data.expiresAt) {
        data.expiresAt = new Date(data.expiresAt);
    }
    return data;
};

const loginResponseDtoSchemaResponseTransformer = (data: any) => {
    data.user = userSchemaResponseTransformer(data.user);
    data.session = sessionSchemaResponseTransformer(data.session);
    return data;
};

export const signInResponseTransformer = async (data: any): Promise<SignInResponse> => {
    data = loginResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const signUpResponseTransformer = async (data: any): Promise<SignUpResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

const userSessionSchemaResponseTransformer = (data: any) => {
    data.user = userSchemaResponseTransformer(data.user);
    data.session = sessionSchemaResponseTransformer(data.session);
    return data;
};

export const getSessionResponseTransformer = async (data: any): Promise<GetSessionResponse> => {
    data = userSessionSchemaResponseTransformer(data);
    return data;
};

export const getCurrentUserResponseTransformer = async (data: any): Promise<GetCurrentUserResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

export const getUserResponseTransformer = async (data: any): Promise<GetUserResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

const subscriptionSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    if (data.currentPeriodStart) {
        data.currentPeriodStart = new Date(data.currentPeriodStart);
    }
    if (data.currentPeriodEnd) {
        data.currentPeriodEnd = new Date(data.currentPeriodEnd);
    }
    if (data.canceledAt) {
        data.canceledAt = new Date(data.canceledAt);
    }
    return data;
};

export const updateSubscriptionResponseTransformer = async (data: any): Promise<UpdateSubscriptionResponse> => {
    data = subscriptionSchemaResponseTransformer(data);
    return data;
};

export const cancelSubscriptionResponseTransformer = async (data: any): Promise<CancelSubscriptionResponse> => {
    data = subscriptionSchemaResponseTransformer(data);
    return data;
};

const sessionStateSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const saveSessionStateResponseTransformer = async (data: any): Promise<SaveSessionStateResponse> => {
    data = sessionStateSchemaResponseTransformer(data);
    return data;
};
