// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

/**
 * Basics
 */
export type Basics = {
    /**
     * Name
     *
     * Full name of the person
     */
    name: string;
    /**
     * Email
     *
     * Email address
     */
    email: string;
    /**
     * Phone
     *
     * Phone number
     */
    phone: string;
    /**
     * Location
     *
     * City, State or full address location
     */
    location: string;
    /**
     * Summary
     *
     * Professional summary or objective statement
     */
    summary: string;
};

/**
 * Body_uploadDocument
 */
export type BodyUploadDocument = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * DocumentData
 */
export type DocumentData = {
    /**
     * Basic personal and contact information
     */
    basics: Basics;
    /**
     * Experience
     *
     * List of work experience entries in chronological order
     */
    experience: Array<Experience>;
    /**
     * Skills
     *
     * List of technical skills, programming languages, tools, or competencies
     */
    skills: Array<string>;
    /**
     * Education
     *
     * List of educational qualifications
     */
    education: Array<Education>;
};

/**
 * DocumentDataOutput
 */
export type DocumentDataOutput = {
    /**
     * Summary
     *
     * Summary of the changes made to the resume
     */
    summary: string;
    /**
     * The updated resume content
     */
    data: DocumentData;
};

/**
 * Education
 */
export type Education = {
    /**
     * Institution
     *
     * School, university, or educational institution name
     */
    institution: string;
    /**
     * Degree
     *
     * Degree type and major (e.g., 'Bachelor of Science in Computer Science')
     */
    degree: string;
    /**
     * Year
     *
     * Graduation year or date range
     */
    year: string;
};

/**
 * Experience
 */
export type Experience = {
    /**
     * Company
     *
     * Company or organization name
     */
    company: string;
    /**
     * Location
     *
     * City, State or full address location of the company
     */
    location?: string | null;
    /**
     * Role
     *
     * Job title or position name
     */
    role: string;
    /**
     * Startdate
     *
     * Start date of employment (format: MM/YYYY or YYYY)
     */
    startDate: string;
    /**
     * Enddate
     *
     * End date of employment (format: MM/YYYY or YYYY, use 'Present' if currently employed)
     */
    endDate: string;
    /**
     * Bullets
     *
     * List of achievement statements or responsibilities for this role
     */
    bullets: Array<string>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginDto
 */
export type LoginDto = {
    /**
     * Username
     *
     * Email address
     */
    username: string;
    /**
     * Password
     *
     * Password
     */
    password: string;
};

/**
 * LoginResponseDto
 */
export type LoginResponseDto = {
    /**
     * User
     */
    user: User;
    /**
     * Session
     */
    session: Session;
};

/**
 * RewriteDocumentRequest
 */
export type RewriteDocumentRequest = {
    /**
     * Inputmessage
     *
     * Input message from the user
     */
    inputMessage: string;
    /**
     * Jobrequirement
     *
     * Job requirement in text format
     */
    jobRequirement: string;
    /**
     * Resumecontent
     *
     * Resume content in text format
     */
    resumeContent: string;
};

/**
 * Session
 */
export type Session = {
    /**
     * Id
     */
    id?: string;
    /**
     * Createdat
     */
    createdAt?: string;
    /**
     * Updatedat
     */
    updatedAt?: string;
    /**
     * Userid
     */
    userId: string;
    /**
     * Sessiontoken
     */
    sessionToken: string;
    /**
     * Expiresat
     */
    expiresAt?: string;
};

/**
 * SignupDto
 */
export type SignupDto = {
    /**
     * Name
     *
     * Name
     */
    name: string;
    /**
     * Username
     *
     * Username
     */
    username: string;
    /**
     * Email
     *
     * Email address
     */
    email: string;
    /**
     * Password
     *
     * Password
     */
    password: string;
};

/**
 * UploadDocumentResult
 */
export type UploadDocumentResult = {
    /**
     * Filekey
     *
     * File key
     */
    fileKey: string;
    /**
     * Fileurl
     *
     * File URL
     */
    fileUrl: string;
    /**
     * Filename
     *
     * Filename
     */
    filename: string;
    /**
     * Filestoragename
     *
     * File name in storage
     */
    fileStorageName: string;
    /**
     * Contenttype
     *
     * Content type
     */
    contentType: string;
    /**
     * Filesize
     *
     * File size
     */
    fileSize: number;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     */
    id?: string;
    /**
     * Createdat
     */
    createdAt?: string;
    /**
     * Updatedat
     */
    updatedAt?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Emailverified
     */
    emailVerified?: boolean;
    /**
     * Stripecustomerid
     */
    stripeCustomerId?: string | null;
};

/**
 * UserSession
 */
export type UserSession = {
    /**
     * User
     */
    user: User;
    /**
     * Session
     */
    session: Session;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type SignInData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/sign-in';
};

export type SignInErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignInError = SignInErrors[keyof SignInErrors];

export type SignInResponses = {
    /**
     * Successful Response
     */
    200: LoginResponseDto;
};

export type SignInResponse = SignInResponses[keyof SignInResponses];

export type SignUpData = {
    body: SignupDto;
    path?: never;
    query?: never;
    url: '/auth/sign-up';
};

export type SignUpErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignUpError = SignUpErrors[keyof SignUpErrors];

export type SignUpResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type SignUpResponse = SignUpResponses[keyof SignUpResponses];

export type SignOutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/sign-out';
};

export type SignOutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/get-session';
};

export type GetSessionResponses = {
    /**
     * Successful Response
     */
    200: UserSession;
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/me';
};

export type GetCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/user/{id}';
};

export type GetUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UploadDocumentData = {
    body: BodyUploadDocument;
    path?: never;
    query?: never;
    url: '/document/upload';
};

export type UploadDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadDocumentError = UploadDocumentErrors[keyof UploadDocumentErrors];

export type UploadDocumentResponses = {
    /**
     * Successful Response
     */
    200: UploadDocumentResult;
};

export type UploadDocumentResponse = UploadDocumentResponses[keyof UploadDocumentResponses];

export type ParseDocumentData = {
    body?: never;
    path?: never;
    query: {
        /**
         * File Key
         */
        file_key: string;
    };
    url: '/document/parse';
};

export type ParseDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ParseDocumentError = ParseDocumentErrors[keyof ParseDocumentErrors];

export type ParseDocumentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExtractDocumentData = {
    body?: never;
    path?: never;
    query: {
        /**
         * File Key
         */
        file_key: string;
    };
    url: '/document/extract';
};

export type ExtractDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExtractDocumentError = ExtractDocumentErrors[keyof ExtractDocumentErrors];

export type ExtractDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentData;
};

export type ExtractDocumentResponse = ExtractDocumentResponses[keyof ExtractDocumentResponses];

export type RewriteDocumentData = {
    body: RewriteDocumentRequest;
    path?: never;
    query?: never;
    url: '/document/rewrite';
};

export type RewriteDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RewriteDocumentError = RewriteDocumentErrors[keyof RewriteDocumentErrors];

export type RewriteDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentDataOutput;
};

export type RewriteDocumentResponse = RewriteDocumentResponses[keyof RewriteDocumentResponses];
