// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

/**
 * Basics
 */
export type Basics = {
    /**
     * Name
     *
     * Full name of the person
     */
    name: string;
    /**
     * Email
     *
     * Email address
     */
    email: string;
    /**
     * Phone
     *
     * Phone number
     */
    phone: string;
    /**
     * Location
     *
     * City, State or full address location
     */
    location: string;
    /**
     * Summary
     *
     * Professional summary or objective statement
     */
    summary: string;
};

/**
 * Body_parseDocument
 */
export type BodyParseDocument = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_uploadDocument
 */
export type BodyUploadDocument = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CancelSubscriptionRequest
 */
export type CancelSubscriptionRequest = {
    /**
     * Cancelimmediately
     *
     * Whether to cancel immediately or at period end
     */
    cancelImmediately?: boolean;
};

/**
 * CheckoutSession
 */
export type CheckoutSession = {
    /**
     * Url
     *
     * Checkout session URL
     */
    url: string;
};

/**
 * CreateCheckoutSessionDto
 */
export type CreateCheckoutSessionDto = {
    /**
     * Priceid
     *
     * Stripe price ID for the subscription
     */
    priceId: string;
    /**
     * Successurl
     *
     * URL to redirect after successful payment
     */
    successUrl: string;
    /**
     * Cancelurl
     *
     * URL to redirect after canceled payment
     */
    cancelUrl: string;
};

/**
 * CreatePortalSessionDto
 */
export type CreatePortalSessionDto = {
    /**
     * Returnurl
     *
     * URL to return to after managing subscription
     */
    returnUrl: string;
};

/**
 * DeleteAccountResponse
 */
export type DeleteAccountResponse = {
    /**
     * Status
     *
     * Status
     */
    status: 'success' | 'failed';
    /**
     * Message
     *
     * Message
     */
    message?: string | null;
};

/**
 * DocumentData
 */
export type DocumentData = {
    /**
     * Basic personal and contact information
     */
    basics: Basics;
    /**
     * Experience
     *
     * List of work experience entries in chronological order
     */
    experience: Array<Experience>;
    /**
     * Skills
     *
     * List of technical skills, programming languages, tools, or competencies
     */
    skills: Array<string>;
    /**
     * Education
     *
     * List of educational qualifications
     */
    education: Array<Education>;
};

/**
 * DocumentDataOutput
 */
export type DocumentDataOutput = {
    /**
     * Summary
     *
     * Summary of the changes made to the resume
     */
    summary: string;
    /**
     * The updated resume content
     */
    data: DocumentData;
};

/**
 * Education
 */
export type Education = {
    /**
     * Institution
     *
     * School, university, or educational institution name
     */
    institution: string;
    /**
     * Degree
     *
     * Degree type and major (e.g., 'Bachelor of Science in Computer Science')
     */
    degree: string;
    /**
     * Year
     *
     * Graduation year or date range
     */
    year: string;
};

/**
 * Experience
 */
export type Experience = {
    /**
     * Company
     *
     * Company or organization name
     */
    company: string;
    /**
     * Location
     *
     * City, State or full address location of the company
     */
    location?: string | null;
    /**
     * Role
     *
     * Job title or position name
     */
    role: string;
    /**
     * Startdate
     *
     * Start date of employment (format: MM/YYYY or YYYY)
     */
    startDate: string;
    /**
     * Enddate
     *
     * End date of employment (format: MM/YYYY or YYYY, use 'Present' if currently employed)
     */
    endDate: string;
    /**
     * Bullets
     *
     * List of achievement statements or responsibilities for this role
     */
    bullets: Array<string>;
};

/**
 * ExtractDocumentRequest
 */
export type ExtractDocumentRequest = {
    /**
     * Filecontent
     *
     * File content in text format
     */
    fileContent: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginDto
 */
export type LoginDto = {
    /**
     * Username
     *
     * Email address
     */
    username: string;
    /**
     * Password
     *
     * Password
     */
    password: string;
};

/**
 * LoginResponseDto
 */
export type LoginResponseDto = {
    /**
     * User
     */
    user: User;
    /**
     * Session
     */
    session: Session;
};

/**
 * Plan
 */
export type Plan = 'free' | 'basic' | 'premium' | 'enterprise';

/**
 * PortalSession
 */
export type PortalSession = {
    /**
     * Url
     *
     * Billing portal session URL
     */
    url: string;
};

/**
 * RewriteDocumentRequest
 */
export type RewriteDocumentRequest = {
    /**
     * Inputmessage
     *
     * Input message from the user
     */
    inputMessage: string;
    /**
     * Jobrequirement
     *
     * Job requirement in text format
     */
    jobRequirement: string;
    /**
     * Resumecontent
     *
     * Resume content in text format
     */
    resumeContent: string;
};

/**
 * SaveSessionStateDto
 */
export type SaveSessionStateDto = {
    /**
     * Documentname
     *
     * Document name
     */
    documentName?: string | null;
    /**
     * Documenturl
     *
     * Document URL
     */
    documentUrl?: string | null;
    /**
     * Documentparsed
     *
     * Document parsed
     */
    documentParsed?: string | null;
    /**
     * Document data
     */
    documentData?: DocumentData | null;
    /**
     * Jobdescription
     *
     * Job description
     */
    jobDescription?: string | null;
};

/**
 * Session
 */
export type Session = {
    /**
     * Id
     */
    id?: string;
    /**
     * Createdat
     */
    createdAt?: string;
    /**
     * Updatedat
     */
    updatedAt?: string;
    /**
     * Userid
     */
    userId: string;
    /**
     * Sessiontoken
     */
    sessionToken: string;
    /**
     * Expiresat
     */
    expiresAt?: string;
};

/**
 * SessionState
 */
export type SessionState = {
    /**
     * Id
     */
    id?: string;
    /**
     * Createdat
     */
    createdAt?: string;
    /**
     * Updatedat
     */
    updatedAt?: string;
    /**
     * Sessionid
     */
    sessionId: string;
    /**
     * Documentname
     */
    documentName?: string | null;
    /**
     * Documenturl
     */
    documentUrl?: string | null;
    /**
     * Documentparsed
     */
    documentParsed?: string | null;
    documentData?: DocumentData | null;
    /**
     * Jobdescription
     */
    jobDescription?: string | null;
};

/**
 * SignupDto
 */
export type SignupDto = {
    /**
     * Name
     *
     * Name
     */
    name: string;
    /**
     * Username
     *
     * Username
     */
    username: string;
    /**
     * Email
     *
     * Email address
     */
    email: string;
    /**
     * Password
     *
     * Password
     */
    password: string;
};

/**
 * Subscription
 */
export type Subscription = {
    /**
     * Id
     */
    id?: string;
    /**
     * Createdat
     */
    createdAt?: string;
    /**
     * Updatedat
     */
    updatedAt?: string;
    /**
     * Userid
     */
    userId: string;
    plan?: Plan;
    /**
     * Stripecustomerid
     */
    stripeCustomerId: string;
    /**
     * Stripesubscriptionid
     */
    stripeSubscriptionId?: string | null;
    /**
     * Stripepriceid
     */
    stripePriceId?: string | null;
    /**
     * Status
     *
     * Subscription status: active, canceled, past_due, etc.
     */
    status?: string;
    /**
     * Currentperiodstart
     */
    currentPeriodStart?: string | null;
    /**
     * Currentperiodend
     */
    currentPeriodEnd?: string | null;
    /**
     * Cancelatperiodend
     */
    cancelAtPeriodEnd?: boolean;
    /**
     * Canceledat
     */
    canceledAt?: string | null;
};

/**
 * UpdateSubscriptionRequest
 */
export type UpdateSubscriptionRequest = {
    /**
     * Priceid
     *
     * Stripe price ID for the new subscription plan
     */
    priceId: string;
};

/**
 * UploadDocumentResult
 */
export type UploadDocumentResult = {
    /**
     * Filekey
     *
     * File key
     */
    fileKey: string;
    /**
     * Fileurl
     *
     * File URL
     */
    fileUrl: string;
    /**
     * Filename
     *
     * Filename
     */
    filename: string;
    /**
     * Filestoragename
     *
     * File name in storage
     */
    fileStorageName: string;
    /**
     * Contenttype
     *
     * Content type
     */
    contentType: string;
    /**
     * Filesize
     *
     * File size
     */
    fileSize: number;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     */
    id?: string;
    /**
     * Createdat
     */
    createdAt?: string;
    /**
     * Updatedat
     */
    updatedAt?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Emailverified
     */
    emailVerified?: boolean;
};

/**
 * UserSession
 */
export type UserSession = {
    /**
     * User
     */
    user: User;
    /**
     * Session
     */
    session: Session;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type SignInData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/sign-in';
};

export type SignInErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignInError = SignInErrors[keyof SignInErrors];

export type SignInResponses = {
    /**
     * Successful Response
     */
    200: LoginResponseDto;
};

export type SignInResponse = SignInResponses[keyof SignInResponses];

export type SignUpData = {
    body: SignupDto;
    path?: never;
    query?: never;
    url: '/auth/sign-up';
};

export type SignUpErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignUpError = SignUpErrors[keyof SignUpErrors];

export type SignUpResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type SignUpResponse = SignUpResponses[keyof SignUpResponses];

export type SignOutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/sign-out';
};

export type SignOutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/get-session';
};

export type GetSessionResponses = {
    /**
     * Successful Response
     */
    200: UserSession;
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type DeleteAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/account';
};

export type DeleteAccountResponses = {
    /**
     * Successful Response
     */
    200: DeleteAccountResponse;
};

export type DeleteAccountResponse2 = DeleteAccountResponses[keyof DeleteAccountResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/me';
};

export type GetCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/user/{id}';
};

export type GetUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UploadDocumentData = {
    body: BodyUploadDocument;
    path?: never;
    query?: never;
    url: '/document/upload';
};

export type UploadDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadDocumentError = UploadDocumentErrors[keyof UploadDocumentErrors];

export type UploadDocumentResponses = {
    /**
     * Successful Response
     */
    200: UploadDocumentResult;
};

export type UploadDocumentResponse = UploadDocumentResponses[keyof UploadDocumentResponses];

export type ParseDocumentData = {
    body: BodyParseDocument;
    path?: never;
    query?: never;
    url: '/document/parse';
};

export type ParseDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ParseDocumentError = ParseDocumentErrors[keyof ParseDocumentErrors];

export type ParseDocumentResponses = {
    /**
     * Response Parsedocument
     *
     * Successful Response
     */
    200: string;
};

export type ParseDocumentResponse = ParseDocumentResponses[keyof ParseDocumentResponses];

export type ExtractDocumentData = {
    body: ExtractDocumentRequest;
    path?: never;
    query?: never;
    url: '/document/extract';
};

export type ExtractDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExtractDocumentError = ExtractDocumentErrors[keyof ExtractDocumentErrors];

export type ExtractDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentData;
};

export type ExtractDocumentResponse = ExtractDocumentResponses[keyof ExtractDocumentResponses];

export type RewriteDocumentData = {
    body: RewriteDocumentRequest;
    path?: never;
    query?: never;
    url: '/document/rewrite';
};

export type RewriteDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RewriteDocumentError = RewriteDocumentErrors[keyof RewriteDocumentErrors];

export type RewriteDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentDataOutput;
};

export type RewriteDocumentResponse = RewriteDocumentResponses[keyof RewriteDocumentResponses];

export type GetSubscriptionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/subscriptions/subscription';
};

export type GetSubscriptionResponses = {
    /**
     * Response Getsubscription
     *
     * Successful Response
     */
    200: Subscription | null;
};

export type GetSubscriptionResponse = GetSubscriptionResponses[keyof GetSubscriptionResponses];

export type UpdateSubscriptionData = {
    body: UpdateSubscriptionRequest;
    path?: never;
    query?: never;
    url: '/subscriptions/subscription';
};

export type UpdateSubscriptionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSubscriptionError = UpdateSubscriptionErrors[keyof UpdateSubscriptionErrors];

export type UpdateSubscriptionResponses = {
    /**
     * Successful Response
     */
    200: Subscription;
};

export type UpdateSubscriptionResponse = UpdateSubscriptionResponses[keyof UpdateSubscriptionResponses];

export type CancelSubscriptionData = {
    body: CancelSubscriptionRequest;
    path?: never;
    query?: never;
    url: '/subscriptions/subscription/cancel';
};

export type CancelSubscriptionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelSubscriptionError = CancelSubscriptionErrors[keyof CancelSubscriptionErrors];

export type CancelSubscriptionResponses = {
    /**
     * Successful Response
     */
    200: Subscription;
};

export type CancelSubscriptionResponse = CancelSubscriptionResponses[keyof CancelSubscriptionResponses];

export type CreateCheckoutSessionData = {
    body: CreateCheckoutSessionDto;
    path?: never;
    query?: never;
    url: '/subscriptions/checkout';
};

export type CreateCheckoutSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCheckoutSessionError = CreateCheckoutSessionErrors[keyof CreateCheckoutSessionErrors];

export type CreateCheckoutSessionResponses = {
    /**
     * Successful Response
     */
    200: CheckoutSession;
};

export type CreateCheckoutSessionResponse = CreateCheckoutSessionResponses[keyof CreateCheckoutSessionResponses];

export type CreatePortalSessionData = {
    body: CreatePortalSessionDto;
    path?: never;
    query?: never;
    url: '/subscriptions/portal';
};

export type CreatePortalSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePortalSessionError = CreatePortalSessionErrors[keyof CreatePortalSessionErrors];

export type CreatePortalSessionResponses = {
    /**
     * Successful Response
     */
    200: PortalSession;
};

export type CreatePortalSessionResponse = CreatePortalSessionResponses[keyof CreatePortalSessionResponses];

export type StripeWebhookData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/subscriptions/webhook';
};

export type StripeWebhookResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSessionStateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/session-state/';
};

export type GetSessionStateResponses = {
    /**
     * Response Getsessionstate
     *
     * Successful Response
     */
    200: SessionState | null;
};

export type GetSessionStateResponse = GetSessionStateResponses[keyof GetSessionStateResponses];

export type SaveSessionStateData = {
    body: SaveSessionStateDto;
    path?: never;
    query?: never;
    url: '/session-state/';
};

export type SaveSessionStateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveSessionStateError = SaveSessionStateErrors[keyof SaveSessionStateErrors];

export type SaveSessionStateResponses = {
    /**
     * Successful Response
     */
    200: SessionState;
};

export type SaveSessionStateResponse = SaveSessionStateResponses[keyof SaveSessionStateResponses];
