import { Provider } from '@/components/ui/provider';
import { Toaster } from '@/components/ui/toaster';
import { Poppins, Quicksand } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';

const poppins = Poppins({ variable: '--font-poppins', subsets: ['latin'], weight: ['400', '600', '800'] });
const quicksand = Quicksand({ variable: '--font-quicksand', subsets: ['latin'], weight: ['400', '600', '700'] });
export const metadata: Metadata = { title: 'Create Next App', description: 'Generated by create next app' };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${poppins.variable} ${quicksand.variable}`}>
				<Provider forcedTheme="dark">
					{children}
					<Toaster />
				</Provider>
			</body>
		</html>
	);
}
