import { Provider } from '@/components/ui/provider';
import { Toaster } from '@/components/ui/toaster';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({ src: '../public/fonts/GeistVF.woff', variable: '--font-geist-sans' });
const geistMono = localFont({ src: '../public/fonts/GeistMonoVF.woff', variable: '--font-geist-mono' });
export const metadata: Metadata = { title: 'Create Next App', description: 'Generated by create next app' };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<Provider>
					{children}
					<Toaster />
				</Provider>
			</body>
		</html>
	);
}
