import { createSystem, defaultConfig, defineConfig } from '@chakra-ui/react';
import { buttonRecipe, inputRecipe } from '@/lib/config/theme.recipe';

export const theme = createSystem(
	defaultConfig,
	defineConfig({
		theme: {
			recipes: {
				button: buttonRecipe,
				input: inputRecipe,
			},
			tokens: {
				fonts: {
					heading: { value: "'Poppins', sans-serif" },
					body: { value: "'Montserrat', sans-serif" },
					mono: { value: 'IBM Plex Mono' },
				},
				colors: {
					light: { light: { value: '#ffffff' }, medium: { value: '#e8e8e8' }, dark: { value: '#d1d1d1' }, content: { value: '#333c4d' } },
					dark: { light: { value: '#2a303c' }, medium: { value: '#242933' }, dark: { value: '#20252e' }, content: { value: '#b2ccd6' } },
					primary: { DEFAULT: { value: '#9fe88d' }, light: { value: '#66cc8a' }, dark: { value: '#9fe88d' }, content: { value: '#091307' } },
					secondary: { DEFAULT: { value: '#ff7d5d' }, light: { value: '#377cfb' }, dark: { value: '#ff7d5d' }, content: { value: '#160503' } },
					accent: { DEFAULT: { value: '#c792e9' }, light: { value: '#f68067' }, dark: { value: '#c792e9' }, content: { value: '#0e0813' } },
					neutral: { DEFAULT: { value: '#1c212b' }, light: { value: '#333c4d' }, dark: { value: '#1c212b' }, content: { value: '#b2ccd6' } },
					info: { DEFAULT: { value: '#28ebff' }, light: { value: '#00b5ff' }, dark: { value: '#28ebff' }, content: { value: '#011316' } },
					success: { DEFAULT: { value: '#62efbd' }, light: { value: '#00a96e' }, dark: { value: '#62efbd' }, content: { value: '#03140d' } },
					warning: { DEFAULT: { value: '#efd057' }, light: { value: '#ffbe00' }, dark: { value: '#efd057' }, content: { value: '#141003' } },
					error: { DEFAULT: { value: '#ffae9b' }, light: { value: '#ff5861' }, dark: { value: '#ffae9b' }, content: { value: '#160b09' } },
				},
			},
			semanticTokens: {
				colors: {
					fg: { DEFAULT: { value: { _light: '{colors.light.content}', _dark: '{colors.dark.content}' } } },
					bg: {
						muted: { value: { _light: '{colors.light.medium}', _dark: '{colors.neutral.dark}' } },
						panel: { value: { _light: '{colors.light.light}', _dark: '{colors.dark.dark}' } },
						subtle: { value: { _light: '{colors.light.light}', _dark: '{colors.dark.medium}' } },
						solid: { value: { _light: '{colors.light.dark}', _dark: '{colors.dark.dark}' } },
					},
					border: { value: { _light: '{colors.gray.200}', _dark: '{colors.gray.900}' } },
					primary: {
						fg: { value: '{colors.primary.content}' },
						contrast: { value: '{colors.primary.content}' },
						solid: { value: { _light: '{colors.primary.light}', _dark: '{colors.primary.dark}' } },
						muted: { value: { _light: '{colors.primary.light}', _dark: '{colors.primary.dark}' } },
						subtle: { value: { _light: '{colors.primary.light}', _dark: '{colors.primary.dark}' } },
						emphasized: { value: { _light: '{colors.primary.light}', _dark: '{colors.primary.dark}' } },
						focusRing: { value: { _light: '{colors.primary.light}', _dark: '{colors.primary.dark}' } },
					},
					secondary: {
						fg: { value: '{colors.secondary.content}' },
						contrast: { value: '{colors.secondary.content}' },
						solid: { value: { _light: '{colors.secondary.light}', _dark: '{colors.secondary.dark}' } },
						muted: { value: { _light: '{colors.secondary.light}', _dark: '{colors.secondary.dark}' } },
						subtle: { value: { _light: '{colors.secondary.light}', _dark: '{colors.secondary.dark}' } },
						emphasized: { value: { _light: '{colors.secondary.light}', _dark: '{colors.secondary.dark}' } },
						focusRing: { value: { _light: '{colors.secondary.light}', _dark: '{colors.secondary.dark}' } },
					},
					accent: {
						fg: { value: '{colors.accent.content}' },
						contrast: { value: '{colors.accent.content}' },
						solid: { value: { _light: '{colors.accent.light}', _dark: '{colors.accent.dark}' } },
						muted: { value: { _light: '{colors.accent.light}', _dark: '{colors.accent.dark}' } },
						subtle: { value: { _light: '{colors.accent.light}', _dark: '{colors.accent.dark}' } },
						emphasized: { value: { _light: '{colors.accent.light}', _dark: '{colors.accent.dark}' } },
						focusRing: { value: { _light: '{colors.accent.light}', _dark: '{colors.accent.dark}' } },
					},
					neutral: {
						fg: { value: '{colors.neutral.content}' },
						contrast: { value: '{colors.neutral.content}' },
						solid: { value: { _light: '{colors.neutral.light}', _dark: '{colors.neutral.dark}' } },
						muted: { value: { _light: '{colors.neutral.light}', _dark: '{colors.neutral.dark}' } },
						subtle: { value: { _light: '{colors.neutral.light}', _dark: '{colors.neutral.dark}' } },
						emphasized: { value: { _light: '{colors.neutral.light}', _dark: '{colors.neutral.dark}' } },
						focusRing: { value: { _light: '{colors.neutral.light}', _dark: '{colors.neutral.dark}' } },
					},
					info: {
						fg: { value: '{colors.info.content}' },
						contrast: { value: '{colors.info.content}' },
						solid: { value: { _light: '{colors.info.light}', _dark: '{colors.info.dark}' } },
						muted: { value: { _light: '{colors.info.light}', _dark: '{colors.info.dark}' } },
						subtle: { value: { _light: '{colors.info.light}', _dark: '{colors.info.dark}' } },
						emphasized: { value: { _light: '{colors.info.light}', _dark: '{colors.info.dark}' } },
						focusRing: { value: { _light: '{colors.info.light}', _dark: '{colors.info.dark}' } },
					},
					success: {
						fg: { value: '{colors.success.content}' },
						contrast: { value: '{colors.success.content}' },
						solid: { value: { _light: '{colors.success.light}', _dark: '{colors.success.dark}' } },
						muted: { value: { _light: '{colors.success.light}', _dark: '{colors.success.dark}' } },
						subtle: { value: { _light: '{colors.success.light}', _dark: '{colors.success.dark}' } },
						emphasized: { value: { _light: '{colors.success.light}', _dark: '{colors.success.dark}' } },
						focusRing: { value: { _light: '{colors.success.light}', _dark: '{colors.success.dark}' } },
					},
					warning: {
						fg: { value: '{colors.warning.content}' },
						contrast: { value: '{colors.warning.content}' },
						solid: { value: { _light: '{colors.warning.light}', _dark: '{colors.warning.dark}' } },
						muted: { value: { _light: '{colors.warning.light}', _dark: '{colors.warning.dark}' } },
						subtle: { value: { _light: '{colors.warning.light}', _dark: '{colors.warning.dark}' } },
						emphasized: { value: { _light: '{colors.warning.light}', _dark: '{colors.warning.dark}' } },
						focusRing: { value: { _light: '{colors.warning.light}', _dark: '{colors.warning.dark}' } },
					},
					error: {
						fg: { value: '{colors.error.content}' },
						contrast: { value: '{colors.error.content}' },
						solid: { value: { _light: '{colors.error.light}', _dark: '{colors.error.dark}' } },
						muted: { value: { _light: '{colors.error.light}', _dark: '{colors.error.dark}' } },
						subtle: { value: { _light: '{colors.error.light}', _dark: '{colors.error.dark}' } },
						emphasized: { value: { _light: '{colors.error.light}', _dark: '{colors.error.dark}' } },
						focusRing: { value: { _light: '{colors.error.light}', _dark: '{colors.error.dark}' } },
					},
				},
			},
		},
	}),
);
