// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { AuthApi, DocumentApi, type Options, SessionStateApi, SubscriptionsApi, UserApi } from '../sdk.gen';
import type { CancelSubscriptionData, CancelSubscriptionError, CancelSubscriptionResponse, ClearSessionStateData, ClearSessionStateResponse, CreateCheckoutSessionData, CreateCheckoutSessionError, CreateCheckoutSessionResponse, CreatePortalSessionData, CreatePortalSessionError, CreatePortalSessionResponse, DeleteAccountData, DeleteAccountResponse2, ExtractDocumentData, ExtractDocumentError, ExtractDocumentResponse, GenerateDocumentData, GetCurrentUserData, GetCurrentUserResponse, GetSessionData, GetSessionResponse, GetSessionStateData, GetSessionStateResponse, GetSubscriptionData, GetSubscriptionResponse, GetUserData, GetUserError, GetUserResponse, ParseDocumentData, ParseDocumentError, ParseDocumentResponse, RewriteDocumentData, RewriteDocumentError, RewriteDocumentResponse, SaveSessionStateData, SaveSessionStateError, SaveSessionStateResponse, SignInData, SignInError, SignInResponse, SignOutData, SignUpData, SignUpError, SignUpResponse, StripeWebhookData, UpdateSubscriptionData, UpdateSubscriptionError, UpdateSubscriptionResponse, UploadDocumentData, UploadDocumentError, UploadDocumentResponse } from '../types.gen';

/**
 * Login
 */
export const signInMutation = (options?: Partial<Options<SignInData>>): UseMutationOptions<SignInResponse, SignInError, Options<SignInData>> => {
    const mutationOptions: UseMutationOptions<SignInResponse, SignInError, Options<SignInData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await AuthApi.signIn({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Signup
 */
export const signUpMutation = (options?: Partial<Options<SignUpData>>): UseMutationOptions<SignUpResponse, SignUpError, Options<SignUpData>> => {
    const mutationOptions: UseMutationOptions<SignUpResponse, SignUpError, Options<SignUpData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await AuthApi.signUp({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const signOutQueryKey = (options?: Options<SignOutData>) => createQueryKey('signOut', options);

/**
 * Sign Out
 */
export const signOutOptions = (options?: Options<SignOutData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof signOutQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await AuthApi.signOut({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: signOutQueryKey(options)
});

export const getSessionQueryKey = (options?: Options<GetSessionData>) => createQueryKey('getSession', options);

/**
 * Get Session
 */
export const getSessionOptions = (options?: Options<GetSessionData>) => queryOptions<GetSessionResponse, DefaultError, GetSessionResponse, ReturnType<typeof getSessionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await AuthApi.getSession({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSessionQueryKey(options)
});

/**
 * Delete Account
 */
export const deleteAccountMutation = (options?: Partial<Options<DeleteAccountData>>): UseMutationOptions<DeleteAccountResponse2, DefaultError, Options<DeleteAccountData>> => {
    const mutationOptions: UseMutationOptions<DeleteAccountResponse2, DefaultError, Options<DeleteAccountData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await AuthApi.deleteAccount({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCurrentUserQueryKey = (options?: Options<GetCurrentUserData>) => createQueryKey('getCurrentUser', options);

/**
 * Get Current User
 */
export const getCurrentUserOptions = (options?: Options<GetCurrentUserData>) => queryOptions<GetCurrentUserResponse, DefaultError, GetCurrentUserResponse, ReturnType<typeof getCurrentUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await UserApi.getCurrentUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCurrentUserQueryKey(options)
});

export const getUserQueryKey = (options: Options<GetUserData>) => createQueryKey('getUser', options);

/**
 * Get User
 */
export const getUserOptions = (options: Options<GetUserData>) => queryOptions<GetUserResponse, GetUserError, GetUserResponse, ReturnType<typeof getUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await UserApi.getUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserQueryKey(options)
});

/**
 * Upload Document
 */
export const uploadDocumentMutation = (options?: Partial<Options<UploadDocumentData>>): UseMutationOptions<UploadDocumentResponse, UploadDocumentError, Options<UploadDocumentData>> => {
    const mutationOptions: UseMutationOptions<UploadDocumentResponse, UploadDocumentError, Options<UploadDocumentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await DocumentApi.uploadDocument({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Parse Document
 */
export const parseDocumentMutation = (options?: Partial<Options<ParseDocumentData>>): UseMutationOptions<ParseDocumentResponse, ParseDocumentError, Options<ParseDocumentData>> => {
    const mutationOptions: UseMutationOptions<ParseDocumentResponse, ParseDocumentError, Options<ParseDocumentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await DocumentApi.parseDocument({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Extract Document
 */
export const extractDocumentMutation = (options?: Partial<Options<ExtractDocumentData>>): UseMutationOptions<ExtractDocumentResponse, ExtractDocumentError, Options<ExtractDocumentData>> => {
    const mutationOptions: UseMutationOptions<ExtractDocumentResponse, ExtractDocumentError, Options<ExtractDocumentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await DocumentApi.extractDocument({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Rewrite Document
 */
export const rewriteDocumentMutation = (options?: Partial<Options<RewriteDocumentData>>): UseMutationOptions<RewriteDocumentResponse, RewriteDocumentError, Options<RewriteDocumentData>> => {
    const mutationOptions: UseMutationOptions<RewriteDocumentResponse, RewriteDocumentError, Options<RewriteDocumentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await DocumentApi.rewriteDocument({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const generateDocumentQueryKey = (options?: Options<GenerateDocumentData>) => createQueryKey('generateDocument', options);

/**
 * Generate Document
 */
export const generateDocumentOptions = (options?: Options<GenerateDocumentData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof generateDocumentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await DocumentApi.generateDocument({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: generateDocumentQueryKey(options)
});

export const getSubscriptionQueryKey = (options?: Options<GetSubscriptionData>) => createQueryKey('getSubscription', options);

/**
 * Get By User Id
 */
export const getSubscriptionOptions = (options?: Options<GetSubscriptionData>) => queryOptions<GetSubscriptionResponse, DefaultError, GetSubscriptionResponse, ReturnType<typeof getSubscriptionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await SubscriptionsApi.getSubscription({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSubscriptionQueryKey(options)
});

/**
 * Update Subscription
 */
export const updateSubscriptionMutation = (options?: Partial<Options<UpdateSubscriptionData>>): UseMutationOptions<UpdateSubscriptionResponse, UpdateSubscriptionError, Options<UpdateSubscriptionData>> => {
    const mutationOptions: UseMutationOptions<UpdateSubscriptionResponse, UpdateSubscriptionError, Options<UpdateSubscriptionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await SubscriptionsApi.updateSubscription({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Cancel Subscription
 */
export const cancelSubscriptionMutation = (options?: Partial<Options<CancelSubscriptionData>>): UseMutationOptions<CancelSubscriptionResponse, CancelSubscriptionError, Options<CancelSubscriptionData>> => {
    const mutationOptions: UseMutationOptions<CancelSubscriptionResponse, CancelSubscriptionError, Options<CancelSubscriptionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await SubscriptionsApi.cancelSubscription({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create Checkout Session
 */
export const createCheckoutSessionMutation = (options?: Partial<Options<CreateCheckoutSessionData>>): UseMutationOptions<CreateCheckoutSessionResponse, CreateCheckoutSessionError, Options<CreateCheckoutSessionData>> => {
    const mutationOptions: UseMutationOptions<CreateCheckoutSessionResponse, CreateCheckoutSessionError, Options<CreateCheckoutSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await SubscriptionsApi.createCheckoutSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create Portal Session
 */
export const createPortalSessionMutation = (options?: Partial<Options<CreatePortalSessionData>>): UseMutationOptions<CreatePortalSessionResponse, CreatePortalSessionError, Options<CreatePortalSessionData>> => {
    const mutationOptions: UseMutationOptions<CreatePortalSessionResponse, CreatePortalSessionError, Options<CreatePortalSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await SubscriptionsApi.createPortalSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Stripe Webhook
 */
export const stripeWebhookMutation = (options?: Partial<Options<StripeWebhookData>>): UseMutationOptions<unknown, DefaultError, Options<StripeWebhookData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<StripeWebhookData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await SubscriptionsApi.stripeWebhook({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Clear Session State
 */
export const clearSessionStateMutation = (options?: Partial<Options<ClearSessionStateData>>): UseMutationOptions<ClearSessionStateResponse, DefaultError, Options<ClearSessionStateData>> => {
    const mutationOptions: UseMutationOptions<ClearSessionStateResponse, DefaultError, Options<ClearSessionStateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await SessionStateApi.clearSessionState({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSessionStateQueryKey = (options?: Options<GetSessionStateData>) => createQueryKey('getSessionState', options);

/**
 * Get Session State
 */
export const getSessionStateOptions = (options?: Options<GetSessionStateData>) => queryOptions<GetSessionStateResponse, DefaultError, GetSessionStateResponse, ReturnType<typeof getSessionStateQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await SessionStateApi.getSessionState({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSessionStateQueryKey(options)
});

/**
 * Save Session State
 */
export const saveSessionStateMutation = (options?: Partial<Options<SaveSessionStateData>>): UseMutationOptions<SaveSessionStateResponse, SaveSessionStateError, Options<SaveSessionStateData>> => {
    const mutationOptions: UseMutationOptions<SaveSessionStateResponse, SaveSessionStateError, Options<SaveSessionStateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await SessionStateApi.saveSessionState({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
