// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { AuthApi, DocumentApi, type Options, UserApi } from '../sdk.gen';
import type { ExtractDocumentData, ExtractDocumentError, ExtractDocumentResponse, GetCurrentUserData, GetCurrentUserResponse, GetSessionData, GetSessionResponse, GetUserData, GetUserError, GetUserResponse, ParseDocumentData, ParseDocumentError, RewriteDocumentData, RewriteDocumentError, RewriteDocumentResponse, SignInData, SignInError, SignInResponse, SignOutData, SignUpData, SignUpError, SignUpResponse, UploadDocumentData, UploadDocumentError, UploadDocumentResponse } from '../types.gen';

/**
 * Login
 */
export const signInMutation = (options?: Partial<Options<SignInData>>): UseMutationOptions<SignInResponse, SignInError, Options<SignInData>> => {
    const mutationOptions: UseMutationOptions<SignInResponse, SignInError, Options<SignInData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await AuthApi.signIn({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Signup
 */
export const signUpMutation = (options?: Partial<Options<SignUpData>>): UseMutationOptions<SignUpResponse, SignUpError, Options<SignUpData>> => {
    const mutationOptions: UseMutationOptions<SignUpResponse, SignUpError, Options<SignUpData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await AuthApi.signUp({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const signOutQueryKey = (options?: Options<SignOutData>) => createQueryKey('signOut', options);

/**
 * Sign Out
 */
export const signOutOptions = (options?: Options<SignOutData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof signOutQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await AuthApi.signOut({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: signOutQueryKey(options)
});

export const getSessionQueryKey = (options?: Options<GetSessionData>) => createQueryKey('getSession', options);

/**
 * Get Session
 */
export const getSessionOptions = (options?: Options<GetSessionData>) => queryOptions<GetSessionResponse, DefaultError, GetSessionResponse, ReturnType<typeof getSessionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await AuthApi.getSession({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSessionQueryKey(options)
});

export const getCurrentUserQueryKey = (options?: Options<GetCurrentUserData>) => createQueryKey('getCurrentUser', options);

/**
 * Get Current User
 */
export const getCurrentUserOptions = (options?: Options<GetCurrentUserData>) => queryOptions<GetCurrentUserResponse, DefaultError, GetCurrentUserResponse, ReturnType<typeof getCurrentUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await UserApi.getCurrentUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCurrentUserQueryKey(options)
});

export const getUserQueryKey = (options: Options<GetUserData>) => createQueryKey('getUser', options);

/**
 * Get User
 */
export const getUserOptions = (options: Options<GetUserData>) => queryOptions<GetUserResponse, GetUserError, GetUserResponse, ReturnType<typeof getUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await UserApi.getUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserQueryKey(options)
});

/**
 * Upload Document
 */
export const uploadDocumentMutation = (options?: Partial<Options<UploadDocumentData>>): UseMutationOptions<UploadDocumentResponse, UploadDocumentError, Options<UploadDocumentData>> => {
    const mutationOptions: UseMutationOptions<UploadDocumentResponse, UploadDocumentError, Options<UploadDocumentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await DocumentApi.uploadDocument({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Parse Document
 */
export const parseDocumentMutation = (options?: Partial<Options<ParseDocumentData>>): UseMutationOptions<unknown, ParseDocumentError, Options<ParseDocumentData>> => {
    const mutationOptions: UseMutationOptions<unknown, ParseDocumentError, Options<ParseDocumentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await DocumentApi.parseDocument({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Extract Document
 */
export const extractDocumentMutation = (options?: Partial<Options<ExtractDocumentData>>): UseMutationOptions<ExtractDocumentResponse, ExtractDocumentError, Options<ExtractDocumentData>> => {
    const mutationOptions: UseMutationOptions<ExtractDocumentResponse, ExtractDocumentError, Options<ExtractDocumentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await DocumentApi.extractDocument({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Rewrite Document
 */
export const rewriteDocumentMutation = (options?: Partial<Options<RewriteDocumentData>>): UseMutationOptions<RewriteDocumentResponse, RewriteDocumentError, Options<RewriteDocumentData>> => {
    const mutationOptions: UseMutationOptions<RewriteDocumentResponse, RewriteDocumentError, Options<RewriteDocumentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await DocumentApi.rewriteDocument({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
